#!/usr/bin/env bash
# (c) 2021 bwmabe
# FILENAME: cryptic-bucket

function print_usage {
	echo "USAGE: cryptic-bucket [COMMAND] [OPTIONS]"
	echo "	create BUCKET_NAME SIZE [FS_TYPE] : Makes a bucket"
	echo "	mount BUCKET_NAME MOUNTPOINT : Mounts a bucket"
	echo "	unmount BUCKET_NAME          : unmounts a bucket"
	echo "	list                         : Lists buckets"
	echo "	help                         : prints this"
	exit $1
}	

function cb_create {
	name=$1
	size=$2
	fs_type=$3

	echo $name $size $fs_type	

	echo "Creating key"
	dd if=/dev/urandom of=$name.key bs=1024 count=4
		
	echo "Creating container"
	dd if=/dev/zero of=$name.img bs=1 seek=$size count=0
	sudo cryptsetup luksFormat $name.img $name.key

	echo "Creating filesystem on container"
	sudo cryptsetup luksOpen $name.img $name --key-file $name.key
	sudo mkfs.$fs_type /dev/mapper/$name

	echo "Encryping key"
	openssl aes-256-cbc -pbkdf2 -in $name.key -out $name.key.enc

	echo "Deleting unencrypted key"
	rm $name.key
}

function cb_mount {
	name=$1
	mount_point=$2

	echo $name $mount_point
}

function cb_unmount {
	echo ""
}

function cb_list {
	echo ""
}

# The 1st argument passed should be the command
cmd=$1

# Shift to pop the first arg, the command. Everything after should be options
shift

case $cmd in

	help | -h | --help)
		print_usage 0
		;;
	create | -c | --create)
		cb_create "$@"
		;;
	*)
		print_usage 1
		;;
esac

# vi:syntax=sh
