#!/usr/bin/env bash
# (c) 2021 bwmabe
# FILENAME: cryptic-bucket

# Openssl command; saved as a variable to type it less often
enc="sudo openssl aes-256-cbc -pbkdf2 "

# Prints the usage either on help or an invalid command
function print_usage {
	echo "USAGE: cryptic-bucket [COMMAND] [OPTIONS]"
	echo "	create BUCKET_NAME SIZE        : Makes a bucket"
	echo "	mount BUCKET_NAME MOUNTPOINT   : Mounts a bucket"
	echo "	unmount BUCKET_NAME MOUNTPOINT : unmounts a bucket"
	echo "	list                           : Lists buckets"
	echo "	help                           : prints this"
	exit $1
}	

# Prints version and copyright info
function print_version {
	echo "cryptic-bucket Version 0.1a"
	echo "This program is Free Software distributed under the MIT License"
	echo "(c) 2021 bwmabe"
	exit 0
}

# Creates a container (bucket)
function cb_create {
	name=$1
	size=$2

	echo "Creating key"
	key=$(dd if=/dev/urandom count=4 status=none | base64)

	echo "Creating container"
	dd if=/dev/zero of=$name.img bs=1 seek=$size count=0 status=none
	echo -n $key | sudo cryptsetup luksFormat $name.img

	echo "Creating filesystem on container"
	echo -n $key | sudo cryptsetup luksOpen $name.img $name
	sudo mkfs.ext4 /dev/mapper/$name

	echo "Encryping key"
	echo -n $key | $enc -out $name.key.enc

	echo -n "Mount the new bucket? (y/n): "
	read yn 
	case $yn in
		y | Y | yes |YES)
			echo -n "Mount '$name' where? (mount point): "
			read mount_point 			
			mount_point="${mount_point/#\~/$HOME}"
			sudo mount /dev/mapper/$name $mount_point
			exit 0
			;;
		*)
			sudo cryptsetup luksClose $name
			exit 0
			;;
	esac
}

# Mounts a container (bucket)
function cb_mount {
	name=$1
	mount_point="${2/#\~/$HOME}"

	echo $name $mount_point
	$enc -d -in $name.key.enc | sudo cryptsetup luksOpen $name.img $name
	sudo mount -t ext4 /dev/mapper/$name $mount_point
}

# Unmounts a container
function cb_unmount {
	name=$1
	mount_point="${2/#\~/$HOME}"
	sudo umount $mount_point
	sudo cryptsetup luksClose $name
}

# Lists buckets; planned to be stored according to the XDG Specification
function cb_list {
	# Should list opened buckets, available buckets, and mounted buckets
	# available is defined as unmounted AND closed
	echo ""
}

# The 1st argument passed should be the command
cmd=$1

# Shift to pop the first arg, the command. Everything after should be options
shift

# Do stuff based on the command
case $cmd in

	help | -h | --help)
		print_usage 0
		;;
	create | -c | --create)
		cb_create "$@"
		;;
	mount | -m | --mount)
		cb_mount "$@"
		;;
	unmount | -u | --unmount | umount | --umount)
		cb_unmount "$@"
		;;
	version | --version)
		print_version
		;;
	*)
		print_usage 1
		;;
esac

# vi:syntax=sh
